cc_binary(
    name = 'test',
    srcs = [
        'test.cc',
        'handle_parse.cc',
        'user.cc'
        ],
    deps = [
        '//toft/base/string:_algorithm',
        '//toft/base/string:_number'
        ]
)